name: Unit

on:
  push:
    branches:
    - main
    tags:
    - '!*'
  pull_request:

env:
  TURBO_REMOTE_ONLY: 'true'
  TURBO_TEAM: 'vercel'
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    name: Unit
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [16]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.13.15'
      - uses: actions/checkout@v3
        with:
            fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node }}
      - name: install pnpm@7.24.2
        run: npm i -g pnpm@7.24.2
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run lint
        if: matrix.os == 'ubuntu-latest' && matrix.node == 14 # only run lint once
      - run: pnpm run test-unit
      - run: pnpm -C packages/cli run coverage
        if: matrix.os == 'ubuntu-latest' && matrix.node == 14 # only run coverage once
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
